//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaim
    {
        public int id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> id_Должность { get; set; }
        public string Дата_Рождения { get; set; }
        public Nullable<int> id_Пол { get; set; }
        public Nullable<decimal> Сумма_займа { get; set; }
    
        public virtual Dol Dol { get; set; }
        public virtual Pol Pol { get; set; }
    }
}
